spring:
  datasource:
    url: jdbc:sqlite::resource:database.sqlite
  sleuth:
    baggage:
      remoteFields:
        - storeId
        - x-vcap-request-id
      tagFields:
        - storeId
    traceId128: true
    propagation-keys: storeId
logging:
  pattern:
    level: "[%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"

wavefront:
  freemium-account: false
  application:
    name: edge-pos-ui
    service: Tanzu-Edge-Store

management:
  metrics: 
    export:
      wavefront:
        uri: proxy://192.168.0.5:2878
        
pos:
  storeId: whichSite