#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: concourse-main
type: Opaque
data:
  harborDomain: #@ base64.encode(data.values.commonSecrets.harborDomain)
  harborUser: #@ base64.encode(data.values.commonSecrets.harborUser)
  harborPassword: #@ base64.encode(data.values.commonSecrets.harborPassword)
  kubeconfigBuildServer: #@ base64.encode(data.values.commonSecrets.kubeconfigBuildServer)
  kubernetesBuildServiceAccountToken: #@ base64.encode(data.values.commonSecrets.kubernetesBuildServiceAccountToken)
  kubernetesBuildCluster: #@ base64.encode(data.values.commonSecrets.kubernetesBuildCluster)
  concourseHelperImage: #@ base64.encode(data.values.commonSecrets.concourseHelperImage)
  pivnetApiToken: #@ base64.encode(data.values.commonSecrets.pivnetApiToken)
  kubernetesDeployServiceAccountToken: #@ base64.encode(data.values.commonSecrets.kubernetesDeployServiceAccountToken)
  kubeconfigDeployServer: #@ base64.encode(data.values.commonSecrets.kubeconfigDeployServer)
  kubernetesDeployCluster: #@ base64.encode(data.values.commonSecrets.kubernetesDeployCluster)
